# Generated by Django 4.0.3 on 2022-04-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Ci')),
                ('nomcliente', models.CharField(max_length=30, verbose_name='Nombre')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Nombre')),
                ('edad', models.IntegerField(max_length=5, verbose_name='Edad')),
                ('numcelular', models.IntegerField(max_length=20, verbose_name='Nº celular')),
            ],
        ),
    ]
