# Generated by Django 4.0.3 on 2022-04-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistematurismo', '0002_alter_cliente_edad_alter_cliente_numcelular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apmaterno',
            field=models.CharField(max_length=30, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='appaterno',
            field=models.CharField(max_length=30, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
    ]
